### ISSUE TITLE
Try to use Constructor injection. Understand differences between variable vs constructor injection

### ISSUE THREAD

**Issue by mvlaicevich** [odhoman/skill-matrix-api#1]
https://github.com/odhoman/skill-matrix-api/blob/ff2e3f9edf064127654b084b25217832a4e02938/src/main/java/com/softvision/skill_matrix_api/controllers/CandidateController.java#L21

**Comment by odhoman** [comment]
DI changes to Constructor in CandidateController, ConsultanController, ConsultantServiceImpl and CandidateServiceImpl.

**Understanding differences between variable vs constructor injection**

- With field injenctio there is a single responsibility principle violation. You can add without restrictions more than one responsibilities. 

- Dependency Hiding: The class is no longer responsible for managing its own dependencies

- DI Container Coupling: when injecting directly into fields, you provide no direct way of instantiating the class with all its required dependencies

- Immutability: field injection cannot be used to assign dependencies to final fields effectively rendering your objects mutable

_Summary from https://www.vojtechruzicka.com/field-dependency-injection-considered-harmful/_

**Comment by mvlaicevich** [comment]
excelent!
